### ISSUE TITLE
Donation buttons glitching on linux

### ISSUE THREAD

**Issue by spectrumgamer75** [adrijano/Text-to-Binary-Converter-v1.1#3]
Hello,
I love your software and it works great, but I face a problem on linux. The donation button (paypal) glitches and gets sunken inside the UI on ubuntu linux. From what I can see in windows screenshots, it is working fine but only on linux this glitch happens. Please fix this issue, if possible as this affects the awesome user interface a bit. Again kudos for the converter :)

**Comment by adrijano** [comment]
hi i will check and fix thist for linux to thank you

**Comment by adrijano** [comment]
its fixed now just start tbc-linux.py

**Comment by spectrumgamer75** [comment]
Thank you for fixing that, also keep making such software. Kudos!
